# Generated by Django 3.2 on 2021-05-04 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OFapp', '0003_rename_collectionmovies_collections_table_movies'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='collections_table',
            table='collections table',
        ),
        migrations.AlterModelTable(
            name='movies_table',
            table='movies table',
        ),
    ]
