# Generated by Django 3.2 on 2021-05-05 23:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('OFapp', '0004_auto_20210504_0539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collections_table',
            name='collectionsuuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
