# Generated by Django 3.2 on 2021-05-06 03:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('OFapp', '0005_alter_collections_table_collectionsuuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies_table',
            name='moviesuuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
